stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: python src/train.py
    deps:
    - data/prepared/train.csv
    - src/train.py
    outs:
    - model/model.joblib
  evaluate:
    cmd: python src/test.py
    deps:
    - model/model.joblib
    - src/test.py
    metrics:
    - metrics/accuracy.json:
        cache: false
